### ISSUE TITLE
NSIS build installer error

### ISSUE THREAD

**Issue by fromasmtodisasm** [dxgldotorg/dxgl#1]
**invalid VIProductVersion format, should be X.X.X.X** - i get this error when attempt build installer

**Comment by dxgldotorg** [comment]
Hi.  At this time the only supported way to build an installer is to checkout the code via SVN:
`svn checkout https://dxgl.org/svn/dxgl` or use TortoiseSVN to checkout.

If you get a server error when checking out use the URL `https://dxgl.org:8443/svn/dxgl` instead.

As a workaround if you do not wish to build an installer, simply copy the ddraw.dll file from the build folder to your game folder, run the game once, then run the dxglcfg.exe file to configure the game profile.

Since I do plan on migrating to GitHub in the future, I will be leaving this bug open for the time being.

**Comment by dxgldotorg** [comment]
I will be marking this as closed, as Git builds now automatically gather the revision information and generate a version number for the executables and installer.

**Comment by dxgldotorg** [comment]
This issue has been resolved by migrating the source code to GitHub.
